odom_topic: "odom_md" # odometry topic for calculating TTC.
frequency: 30.0 # loop running frequency in hz
goal_resume_time: 3.0 # goal resume publish delay

# kp: 5.0
# ki: 2.0
# kd: 1.0
# ttc_desired: 10.0

# ttc_limit: 3.0 # default 2.0